# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitmeuser',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
