# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FitMeUser',
            new_name='FitKickUser',
        ),
    ]
