# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fs_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
