# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0002_auto_20160320_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_set', models.DateField(auto_created=True)),
                ('calories', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('vitamin_a', models.IntegerField()),
                ('vitamin_c', models.IntegerField()),
                ('iron', models.IntegerField()),
                ('calcium', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
