# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_auto_20160321_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
