# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_squashed_0012_auto_20160318_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='routine',
            name='type',
            field=models.CharField(choices=[('M', 'Maintenance'), ('B', 'Bulking'), ('C', 'Cutting')], default='M', max_length=1),
        ),
    ]
