# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('supplementation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
                model_name='supplement',
                name='id',
                field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
                model_name='supplementlog',
                name='id',
                field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
